# 1. Hello, Python

## Hello, Python!

In [ ]:
#Variable assignment
spam_amount = 0

#Function calls
print(spam_amount)

#Reassigning value
spam_amount = spam_amount + 4

if spam_amount > 0:
  print("But I don't want ANY spam!")

viking_song = "Spam " * spam_amount
print(viking_song) 

0
But I don't want ANY spam!
Spam Spam Spam Spam 


## Numbers and arithmetic in Python

In [ ]:
spam_amount = 0
type(spam_amount)

int

In [ ]:
type(19.95)

float

In [ ]:
print(5/2)
print(6/2)

2.5
3.0


In [ ]:
print(5 // 2)
print(6 // 2)

2
3


### Order of operations

In [ ]:
8 - 3 + 2

7

In [ ]:
-3 + 4 * 2

5

In [ ]:
hat_height_cm = 25
my_height_cm = 190

total_height_meters = hat_height_cm + my_height_cm / 100
print("Height in meters =", total_height_meters,"?")

Height in meters = 26.9 ?


In [ ]:
total_height_meters = (hat_height_cm + my_height_cm) / 100
print("Height in meters =", total_height_meters)

Height in meters = 2.15


### Builtin functions for working with numbers

In [ ]:
print(min(1,2,3))
print(max(1,2,3))

1
3


In [ ]:
print(abs(32))
print(abs(-32))

32
32


In [ ]:
print(float(10))
print(int(3.33))

10.0
3


#2. Functions and Getting Help

## Getting Help

In [ ]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [ ]:
# help(round(-2.01))

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



## Defining functions

In [ ]:
# def least_difference(a, b, c):
#   diff1 = abs(a - b)
#   diff2 = abs(b - c)
#   diff3 = abs(a - c)

#   return (min(diff1, diff2, diff3))

In [ ]:
# print(
#     least_difference(1,10,100), 
#     least_difference(1,10,10), 
#     least_difference(5,6,7)
# )

9 0 1


In [ ]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)



### Docstrings

In [ ]:
# def least_difference(a, b, c):
#   """
#   Return the smallest difference between any two numbers among a, b and c.

#   >>> least_difference(1,5,-5)
#   4
#   """
#   diff1 = abs(a - b)
#   diff2 = abs(b - c)
#   diff3 = abs(a - c)

#   return (min(diff1, diff2, diff3))

In [ ]:
# help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)
    Return the smallest difference between any two numbers among a, b and c.
    
    >>> least_difference(1,5,-5)
    4



## Functions that don't return

In [ ]:
def least_difference(a, b, c):
  """
  Return the smallest difference between any two numbers among a, b and c.

  >>> least_difference(1,5,-5)
  4
  """
  diff1 = abs(a - b)
  diff2 = abs(b - c)
  diff3 = abs(a - c)

  min(diff1, diff2, diff3)

In [ ]:
print(
    least_difference(1,10,100), 
    least_difference(1,10,10), 
    least_difference(5,6,7)
)

None None None


In [ ]:
mystery = print()
print(mystery)


None


## Default arguments

In [ ]:
print(1,2,3, sep=' < ')

1 < 2 < 3


In [ ]:
print(1,2,3)

1 2 3


In [ ]:
def greet(who="Colin"):
  print("Hello,", who)

greet()
greet(who="Kaggle")
greet("world")

Hello, Colin
Hello, Kaggle
Hello, world


## Functions Applied to Functions

In [ ]:
def mult_by_five(x):
  return 5*x

def call(fn, arg):
  """Call fn on arg"""
  return fn(arg)

def squared_call(fn, arg):
  """Call fn on the result of calling fn on arg"""
  return fn(fn(arg))

print(
    call(mult_by_five, 1),
    squared_call(mult_by_five, 1),
    sep='\n'
)

5
25


In [ ]:
def mod_5(x):
  """Return the remainder of x after dividing by 5"""
  return x % 5

print(
    'Which number is biggest?',
    max(100,51,14),
    'Which number is the biggest modulo 5',
    max(100,51, 14, key=mod_5),
    sep="\n"
)

Which number is biggest?
100
Which number is the biggest modulo 5
14


#3. Booleans and Conditionals

## Booleans

In [ ]:
x = True
print(x)
print(type(x))

True
<class 'bool'>


In [ ]:
def can_run_for_president(age):
  """Can someone of the given age run for president in the US?"""

  return age >=35

print("Can a 19-year-old run for president?", can_run_for_president(19))
print("Can a 45-year-old run for president?", can_run_for_president(45))

Can a 19-year-old run for president? False
Can a 45-year-old run for president? True


In [ ]:
3.0 == 3

True

In [ ]:
'3' == 3

False

In [ ]:
def is_odd(n):
  return (n%2) == 1

print("Is 100 odd?", is_odd(100))
print("Is -1 odd?", is_odd(-1))

Is 100 odd? False
Is -1 odd? True


## Combining Boolean Values


In [ ]:
def can_run_for_president(age, is_natural_born_citizen):
  """Can someone of the given age and citizenship run for president in the US?"""

  return is_natural_born_citizen and age >= 35

print("Can a 19-year-old run for president?", can_run_for_president(19,True))
print("Can a 45-year-old run for president?", can_run_for_president(55, False))
print("Can a 45-year-old run for president?", can_run_for_president(55, True))

Can a 19-year-old run for president? False
Can a 45-year-old run for president? False
Can a 45-year-old run for president? True


In [ ]:
True or True and False

True

##Conditionals

In [ ]:
def inspect(x):
  if x == 0:
    print(x, "is zero")
  elif x > 0:
    print(x, "is positive")
  elif x < 0:
    print(x, "is negative")
  else:
    print(x, "is unlike anything I've ever seen...")

inspect(0)
inspect(-15)

0 is zero
-15 is negative


In [ ]:
def f(x):
  if x > 0:
    print("Only printed when x is positive; x =",x)
    print("Also only printed when x is positive; x =",x)
  print("Always printed, regardless of x's value; x =",x)

f(1)
f(0)


Only printed when x is positive; x = 1
Also only printed when x is positive; x = 1
Always printed, regardless of x's value; x = 1
Always printed, regardless of x's value; x = 0


## Boolean conversion


In [ ]:
print(bool(1))
print(bool(0))
print(bool("asf"))
print(bool(""))

True
False
True
False


In [ ]:
if 0:
  print(0)
elif "spam":
  print("spam")

spam


#4. Lists

## Lists

In [ ]:
primes = [2, 3, 5, 7]

planets = ['Mercury','Venus','Earth','Mars','Jupiter','Saturn','Uranus','Neptune']

hands = [
    ['J','Q','K'],
    ['2','2','2'],
    ['6','A','K']
]

my_favourite_things = [32, 'raindrops on roses', help]

## Indexing

In [ ]:
planets[0]

'Mercury'

In [ ]:
planets[1]

'Venus'

In [ ]:
planets[-1]

'Neptune'

In [ ]:
planets[-2]

'Uranus'

## Slicing

In [ ]:
planets[0:3]

['Mercury', 'Venus', 'Earth']

In [ ]:
planets[:3]

['Mercury', 'Venus', 'Earth']

In [ ]:
planets[3:]

['Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [ ]:
planets[1:-1]

['Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus']

In [ ]:
planets[-3:]

['Saturn', 'Uranus', 'Neptune']

## Changing lists

In [ ]:
planets[3] = 'Malacandra'
planets

['Mercury',
 'Venus',
 'Earth',
 'Malacandra',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune']

In [ ]:
planets[:3] = ['Mur','Vee','Ur']
print(planets)

planets[:4] = ['Mercury','Venus','Earth','Mars']

['Mur', 'Vee', 'Ur', 'Malacandra', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


## List functions

In [ ]:
len(planets)

8

In [ ]:
sorted(planets)

['Earth', 'Jupiter', 'Mars', 'Mercury', 'Neptune', 'Saturn', 'Uranus', 'Venus']

In [ ]:
primes = [2, 3, 5, 7]
sum(primes)

17

In [ ]:
max(primes)

7

## Interlude: objects

In [ ]:
x = 12

print(x.imag)

c = 12 + 3j
print(c.imag)

0
3.0


In [ ]:
x.bit_length()

4

In [ ]:
help(x.bit_length)

Help on built-in function bit_length:

bit_length() method of builtins.int instance
    Number of bits necessary to represent self in binary.
    
    >>> bin(37)
    '0b100101'
    >>> (37).bit_length()
    6



##List methods

In [ ]:
planets.append('Pluto')

In [ ]:
help(planets.append)

Help on built-in function append:

append(object, /) method of builtins.list instance
    Append object to the end of the list.



In [ ]:
planets

['Mercury',
 'Venus',
 'Earth',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune',
 'Pluto']

In [ ]:
planets.pop()

'Pluto'

In [ ]:
planets

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

###Searching lists

In [ ]:
planets.index('Earth')

2

In [ ]:
# planets.index('Pluto')

In [ ]:
'Earth' in planets

True

In [ ]:
'Calbefraques' in planets

False

In [ ]:
help(planets)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

## Tuples

In [ ]:
t = (1,2,3)

In [ ]:
t = 1, 2, 3
t

(1, 2, 3)

In [ ]:
# t[0] = 100

In [ ]:
x = 0.125
x.as_integer_ratio()

(1, 8)

In [ ]:
numerator, denominator = x.as_integer_ratio()
print(numerator / denominator)

0.125


In [ ]:
a = 1
b = 0
a, b = b, a
print(a,b)

0 1


#5. Loops and List Comprehensions

##Loops

In [ ]:
planets = ['Mercury','Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
  print(planet, end=" ")

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [ ]:
multiplicands = (2, 2, 2, 3, 3, 5)
product = 1
for mult in multiplicands:
  product = product * mult
product

360

In [ ]:
s = 'steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg = ''

for char in s:
  if char.isupper():
    print(char, end='')

HELLO

### range

In [ ]:
for i in range(5):
  print("Doing important work. i=", i)

Doing important work. i= 0
Doing important work. i= 1
Doing important work. i= 2
Doing important work. i= 3
Doing important work. i= 4


###`while` loops

In [ ]:
i = 0
while i < 10:
  print(i, end=" ")
  i += 1

0 1 2 3 4 5 6 7 8 9 

## List comprehensions

In [ ]:
squares = [n**2 for n in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
squares = []
for n in range(10):
  squares.append(n**2)

squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
short_planets = [planet for planet in planets if len(planet) < 6]
short_planets

['Venus', 'Earth', 'Mars']

In [ ]:
loud_short_planets = [
                      planet.upper() + '!' 
                      for planet in planets 
                      if len(planet) < 6]
loud_short_planets

['VENUS!', 'EARTH!', 'MARS!']

In [ ]:
[32 for planet in planets]

[32, 32, 32, 32, 32, 32, 32, 32]

In [ ]:
def count_negatives(nums):
  """
  Return the number of negative numbers in the given list.

  >>> count_negatives([5, -1, -2, 0, 3])
  2
  """
  n_negative = 0
  for num in nums:
    if num < 0:
      n_negative = n_negative + 1
  return n_negative

#6. Strings and Dictionaries

## Strings

### String syntax

In [1]:
x = 'Pluto is a planet'
y = "Pluto is a planet"
x == y

True

In [2]:
print("Pluto's a planet!")
print('My dog is named "Pluto"')

Pluto's a planet!
My dog is named "Pluto"


In [4]:
# 'Pluto's a planet!'

In [5]:
'Pluto\'s a planet!'

"Pluto's a planet!"

In [7]:
hello = "hello\nworld"
print(hello)

hello
world


In [8]:
triplequoted_hello = """hello
world"""
print(triplequoted_hello)
triplequoted_hello == hello

hello
world


True

In [11]:
print("hello")
print("world")
print("hello", end="")
print("pluto", end='')

hello
world
hellopluto

###Strings are sequences

In [12]:
# Indexing
planet = 'Pluto'
planet[0]

'P'

In [13]:
# Slicing
planet[-3:]

'uto'

In [14]:
len(planet)

5

In [15]:
[char+'!' for char in planet]

['P!', 'l!', 'u!', 't!', 'o!']

In [17]:
# planet[0] = 'B'

###String methods

In [18]:
claim = "Pluto is a planet!"
claim.upper()

'PLUTO IS A PLANET!'

In [19]:
claim.lower()

'pluto is a planet!'

In [20]:
claim.index("plan")

11

In [21]:
claim.startswith(planet)

True

In [22]:
claim.endswith('planet')

False

####Going between strings and lists: `.split()` and `.join()`

In [24]:
words = claim.split()
words

['Pluto', 'is', 'a', 'planet!']

In [29]:
datestr = '1956-01-31'
year, month, day = datestr.split('-')

In [30]:
'/'.join([month, day, year])

'01/31/1956'

In [31]:
' 👏 '.join([word.upper() for word in words])

'PLUTO 👏 IS 👏 A 👏 PLANET!'

####Building strings with `.format()`

In [32]:
planet + ', we miss you.'

'Pluto, we miss you.'

In [33]:
position = 9
planet + ", you'll always be the " + str(position) + "th planet to me."

"Pluto, you'll always be the 9th planet to me."

In [34]:
"{}, you'll always be the {}th planet to me.".format(planet, position)

"Pluto, you'll always be the 9th planet to me."

In [37]:
pluto_mass = 1.303 * 10**22
earth_mass = 5.9722 * 10**24
population  = 52910390

"{} weights about {:.2} kilogram ({:.3%} of Earth's mass). It is home to {:,} Plutonians.". format(planet, pluto_mass, pluto_mass / earth_mass, population)

"Pluto weights about 1.3e+22 kilogram (0.218% of Earth's mass). It is home to 52,910,390 Plutonians."

In [38]:
s = """Pluto's a {0}
No, it's a {1}.
{0}!
{1}!""".format('planet','dwarf planet')
print(s)

Pluto's a planet
No, it's a dwarf planet.
planet!
dwarf planet!


## Dictionaries

In [39]:
numbers = {"one":1, "two":2, "three":3}

In [40]:
numbers['one']

1

In [42]:
numbers['eleven'] = 11
numbers

{'eleven': 11, 'one': 1, 'three': 3, 'two': 2}

In [43]:
numbers['one'] = 'Pluto'
numbers

{'eleven': 11, 'one': 'Pluto', 'three': 3, 'two': 2}

In [45]:
planets = ["Mercury", 'Venus', 'Earth', 'Mars', 'Jupiter','Saturn', 'Uranus', 'Neptune']
planet_to_initial = {planet: planet[0] for planet in planets}
planet_to_initial

{'Earth': 'E',
 'Jupiter': 'J',
 'Mars': 'M',
 'Mercury': 'M',
 'Neptune': 'N',
 'Saturn': 'S',
 'Uranus': 'U',
 'Venus': 'V'}

In [46]:
'Saturn' in planet_to_initial

True

In [47]:
'Betelgeuse' in planet_to_initial

False

In [48]:
for k in numbers:
  print('{} = {}'.format(k, numbers[k]))

one = Pluto
two = 2
three = 3
eleven = 11


In [49]:
' '.join(sorted(planet_to_initial.values()))

'E J M M N S U V'

In [50]:
for planet, initial in planet_to_initial.items():
  print("{} begins with \"{}\"".format(planet.rjust(10), initial))

   Mercury begins with "M"
     Venus begins with "V"
     Earth begins with "E"
      Mars begins with "M"
   Jupiter begins with "J"
    Saturn begins with "S"
    Uranus begins with "U"
   Neptune begins with "N"


In [51]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self,

#7. Working with External Libraries

## Imports

In [52]:
import math
print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [53]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [54]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [56]:
math.log(32,2)

5.0

In [58]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [60]:
# help(math)

###Other import syntax

In [61]:
import math as mt
mt.pi

3.141592653589793

In [62]:
from math import *
print(pi, log(32,2))

3.141592653589793 5.0


###Submodules


In [64]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...", dir(numpy.random)[-15:])

numpy.random is a <class 'module'>
it contains names such as... ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [66]:
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([4, 1, 1, 5, 4, 1, 3, 2, 1, 2])

In [68]:
type(rolls)

numpy.ndarray

In [69]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [67]:
rolls.mean()

2.4

In [71]:
rolls.tolist()

[4, 1, 1, 5, 4, 1, 3, 2, 1, 2]

In [72]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [73]:
help(rolls)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

### Operator overloading

In [76]:
# [3, 4, 1, 2, 2, 1] + 10

In [75]:
rolls + 10

array([14, 11, 11, 15, 14, 11, 13, 12, 11, 12])

In [77]:
rolls <= 3

array([False,  True,  True, False, False,  True,  True,  True,  True,
        True])

In [78]:
xlist = [[1,2,3],[2,4,6]]

x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [81]:
x[1,-1]

6

In [82]:
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(1)

a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>